/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'debop' at '14. 5. 26 오후 10:32' with Gradle 1.12
 *
 * @author debop, @date 14. 5. 26 오후 10:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
